<?php

namespace AppBundle\Repository;

/**
 * OutletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OutletRepository extends \Doctrine\ORM\EntityRepository
{
}
